site_name: 科大云盘用户手册
site_url: https://pan.ustc.edu.cn/doc/
repo_url: https://github.com/wf0229/pan_doc
repo_name: Github

nav:
        - 首页: index.md
        - 安装指南: install/index.md
        - 个人云盘: personal/index.md
        - 群组云盘: group/index.md
        - 常见问题: faq/index.md

theme:
        name: material
        language: zh
        palette:
                primary: indigo
                accent: indigo

markdown_extensions:
        - toc:
                permalink: true
        - tables
        - admonition
        - codehilite
