site_name: 科大云盘用户手册
site_url: https://pan.ustc.edu.cn/doc/
repo_url: https://github.com/wf0229/pan_doc
repo_name: Github

nav:
        - 开始使用: 
                - 系统简介: index.md
                - 注册登录: register.md
                - 安装客户端: install.md
        - 功能介绍: 
                - 关于资料库: library.md
                - 个人云盘: private.md
                - 群组云盘: group.md 
        - 常见问题: faq.md

theme:
        name: material
        language: zh
        features:
                - navigation.expand 
        palette:
                primary: indigo
                accent: indigo

markdown_extensions:
        - toc:
                permalink: true
        - tables
        - admonition
        - codehilite
